# ビルド環境
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY ./app .
RUN yarn install
RUN yarn build

# 本番環境
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
