version: "3"
services:
  proxy:
    build: ./proxy
    ports:
      - "9000:9000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "9999:9999"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/go/src/github.com/kikils/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/app:/app
    depends_on:
      - proxy
